on:
  push:
    branches:
      - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.23'
      - uses: actions/checkout@v3
      # ./... はgolang特有のもので、特定のディレクトリとその配下のサブディレクトリ全てを含むことを意味する
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0